### ISSUE TITLE
Orderings not working

### ISSUE THREAD

**Issue by evaferreira** [CHH/jekyll-prismic#9]
I know this is an old repo but perhaps you can help me!

I'm trying to order posts but it doesn't seem to have any effect on the returned collection. I'm using:

```yaml
collections:
        posts:
            # Query the documents by type
            type: post
            # Collection name
            form: posts
            permalink: /news/:uid/
            orderings: '[my.post.date]'
            # Layout file for this collection
            layout: post.html
            output: true
```

It works ok when I try it on the Prismic.io Browser API but no effect at all on how Jekyll displays them and no error message :(

If you have any idea on how to fix this I'll be very thankful!
